//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentHunt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int aid { get; set; }
        public string aname { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string photo { get; set; }
    }
}
