//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentHunt.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class productionevent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productionevent()
        {
            this.eventrequires = new HashSet<eventrequire>();
            this.ratings = new HashSet<rating>();
            this.userapplies = new HashSet<userapply>();
            this.userselects = new HashSet<userselect>();
        }
    
        public int peid { get; set; }
        public int pid { get; set; }
        public string ename { get; set; }
        public string etype { get; set; }
        public string emanager { get; set; }
        public DateTime startdate { get; set; }
        public DateTime enddate { get; set; }
        public string evenu { get; set; }
        public int evisitors { get; set; }
        public DateTime appdeadline { get; set; }
        public string description { get; set; }
        public string image { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventrequire> eventrequires { get; set; }
        public virtual production production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rating> ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userapply> userapplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userselect> userselects { get; set; }
    }
}
