//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentHunt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userprofile
    {
        public int upid { get; set; }
        public int userid { get; set; }
        public int tid { get; set; }
        public int experience { get; set; }
        public string portfolio { get; set; }
    
        public virtual talent talent { get; set; }
        public virtual user user { get; set; }
    }
}
